# This file configures the app which serves public web traffic on google cloud kubernetes
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: first-app
          # Replace $GCLOUD_PROJECT with your project ID
          image: gcr.io/luckylead-kubernetes-test/test:latest
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
